# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cfdf3726dd407e9c72a767c1b8a5420bb06af0f308e886e03b47a7c054f0a015d4a451369b9c20a792f56dbed178b95760ae8068ccc5799f3fd64a1b6df1131

test:
  secret_key_base: 1c6a35ba86a735325b2680a62777cb4a3edc70ad743970bc889fa64ceeb96e445e0768241945049a0934b92875e19f4b8b595c5c6a97764dc8a58fe5b924c824

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
